const LoadDataBase = require("./src/loaders/dataBase.js")
const webServer = require("./src/loaders/webserver.js")
const backups = require("./src/loaders/databaseBackUp.js")
const assetLoading = require("./src/loaders/assetLoader.js")
console.log("Running app!")
