const LoadDataBase = require("./src/loaders/dataBase.js")
const env = require("dotenv").config()
const webServer = require("./src/loaders/webserver.js")
const { bot } = require("./src/loaders/discord/bot.js")
const { loadEvents } = require("./src/loaders/discord/events.js")
const { loadHelper } = require("./src/loaders/discord/helpers.js")
const { loadSlashCommands } = require("./src/loaders/discord/slashCommands.js")
bot.login(process.env.token)
loadEvents()
loadHelper()
loadSlashCommands()
console.log("Running app!")
